//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.11.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=TULAVOI\\HOANGVU;Initial Catalog=DrivingSchool;Integrated Security=Tru" +
            "e;TrustServerCertificate=True")]
        public string DrivingSchoolConnectionString {
            get {
                return ((string)(this["DrivingSchoolConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=TULAVOI\\HOANGVU;Initial Catalog=DrivingSchool;Integrated Security=Tru" +
            "e;Encrypt=True;TrustServerCertificate=True")]
        public string DrivingSchoolConnectionString1 {
            get {
                return ((string)(this["DrivingSchoolConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DANOITXD\\SQLEXPRESS;Initial Catalog=DrivingSchool;Integrated Security" +
            "=True;Encrypt=True;TrustServerCertificate=True")]
        public string DrivingSchoolConnectionString2 {
            get {
                return ((string)(this["DrivingSchoolConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=TULAVOI\\HOANGVU;Initial Catalog=DrivingSchool_V2;Integrated Security=" +
            "True;TrustServerCertificate=True")]
        public string DrivingSchool_V2ConnectionString {
            get {
                return ((string)(this["DrivingSchool_V2ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DANOITXD\\SQLEXPRESS;Initial Catalog=DrivingSchool_V2;Integrated Secur" +
            "ity=True;TrustServerCertificate=True")]
        public string DrivingSchool_V2ConnectionString1 {
            get {
                return ((string)(this["DrivingSchool_V2ConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=TULAVOI\\HOANGVU;Initial Catalog=DrivingSchool_V2;Integrated Security=" +
            "True;Encrypt=True;TrustServerCertificate=True")]
        public string DrivingSchool_V2ConnectionString2 {
            get {
                return ((string)(this["DrivingSchool_V2ConnectionString2"]));
            }
        }
    }
}
